import { forwardRef } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import { COLORS, FONTS, SPACING, RADIUS } from '../constants/theme';

const ShareCard = forwardRef(({ topic, difficulty, content }, ref) => {
  const trimmed = content?.length > 320 ? content.slice(0, 320) + '...' : content;

  return (
    <View ref={ref} style={styles.card} collapsable={false}>
      {/* Header */}
      <View style={styles.header}>
        <View style={styles.iconWrap}>
          <Ionicons name="bulb" size={20} color={COLORS.primary} />
        </View>
        <View>
          <Text style={styles.appName}>Elucid</Text>
          <Text style={styles.tagline}>AI-Powered Tutor</Text>
        </View>
        <View style={styles.badge}>
          <Text style={styles.badgeText}>{difficulty?.toUpperCase()}</Text>
        </View>
      </View>

      {/* Divider */}
      <View style={styles.divider} />

      {/* Topic */}
      <Text style={styles.topic}>{topic}</Text>

      {/* Content */}
      <Text style={styles.content}>{trimmed}</Text>

      {/* Footer */}
      <View style={styles.footer}>
        <Ionicons name="sparkles" size={12} color={COLORS.primary} />
        <Text style={styles.footerText}>Generated by Elucid AI</Text>
      </View>
    </View>
  );
});

export default ShareCard;

const styles = StyleSheet.create({
  card: {
    width: 340,
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.xl,
    padding: SPACING.lg,
    borderWidth: 1.5,
    borderColor: COLORS.border,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  iconWrap: {
    width: 38,
    height: 38,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.primary + '20',
    alignItems: 'center',
    justifyContent: 'center',
  },
  appName: {
    color: COLORS.text,
    fontSize: FONTS.sizes.callout,
    fontWeight: '700',
  },
  tagline: {
    color: COLORS.textTertiary,
    fontSize: FONTS.sizes.caption1,
  },
  badge: {
    marginLeft: 'auto',
    backgroundColor: COLORS.primary + '25',
    borderRadius: RADIUS.full,
    paddingHorizontal: SPACING.sm + 2,
    paddingVertical: SPACING.xs,
  },
  badgeText: {
    color: COLORS.primary,
    fontSize: FONTS.sizes.caption2,
    fontWeight: '700',
  },
  divider: {
    height: 1,
    backgroundColor: COLORS.border,
    marginBottom: SPACING.md,
  },
  topic: {
    color: COLORS.text,
    fontSize: FONTS.sizes.title3,
    fontWeight: '700',
    marginBottom: SPACING.sm,
    letterSpacing: -0.3,
  },
  content: {
    color: COLORS.textSecondary,
    fontSize: FONTS.sizes.subhead,
    lineHeight: 22,
    marginBottom: SPACING.md,
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingTop: SPACING.sm,
  },
  footerText: {
    color: COLORS.primary,
    fontSize: FONTS.sizes.caption1,
    fontWeight: '600',
  },
});